services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: random
      POSTGRES_DB: local_pg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - "6384:6384"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: